services:
  pg:
    image: postgres:18.2
    hostname: pg
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - "6432:5432"
    networks:
      - otushw-network
    volumes:
      - pg_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s

  redis:
    image: redis:8.4.0-alpine
    hostname: redis
    ports:
      - "6379:6379"
    networks:
      - otushw-network
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s

  otushw-web-back:
    image: otushw-web-back:1.0.0
    hostname: otushw-web-back
    build:
      context: ./otushw-web-back
    depends_on:
      pg:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      RUST_LOG: info
      OTHW_PG_CONNECTION_STRING: postgresql://postgres:password@pg:5432/postgres
      OTHW_CITUS_CONNECTION_STRING: postgresql://postgres:password@pg:5432/postgres
      OTHW_REDIS_CONNECTION_STRING: redis://redis/
      OTHW_USE_REDIS: false
      OTHW_FEED_LIMIT: 100
    ports:
      - "8080:8080"
    networks:
      - otushw-network

volumes:
  postgres_data:
  pg_data:
  redis_data:

networks:
  otushw-network:
