[package]
name = "otushw-web-back"
version = "1.0.0"
edition = "2024"

[dependencies]
envy = { version = "0.4.2" }
actix-web = { version = "4.13.0" }
actix-web-httpauth = { version = "0.8.2" }
serde = { version = "1.0.228", features = ["derive", "std"] }
serde_json = { version = "1.0.149" }
postgres = { version = "0.19.12" }
refinery = { version = "0.9.0", features = ["postgres", "int8-versions"] }
bb8 = { version = "0.9.1" }
bb8-postgres = { version = "0.9.0" }
tokio-postgres = { version = "0.7.16", features = ["with-chrono-0_4", "with-uuid-1", "with-time-0_3"] }
log = { version = "0.4.29" }
env_logger = { version = "0.11.10" }
chrono = { version = "0.4.44", features = ["serde"] }
thiserror = { version = "2.0.18" }
argon2 = { version = "0.6.0-rc.8", features = ["getrandom"] }
uuid = { version = "1.22.0", features = ["v4", "serde"] }
jsonwebtoken = { version = "10.3.0", features = ["rust_crypto"] }
redis = { version = "1.1.0", features = ["tokio-comp", "json"] }
bb8-redis = { version = "0.26.0" }
